apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  labels:
    app: loadbalancer-service
spec:
  type: LoadBalancer
  ports:
    - port: 8888
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: loadbalancer-service