golangApp:
  name: golang-for-elympics
  image:
    repository: localhost:5001/rekrutacja_elympics-golang_for_elympics:latest
    ports:
      containerPort: 8081
  service:
    type: ClusterIP
    protocol: TCP
    port: 8081

aspnetApp:
  name: aspnet-for-elympics
  image:
    repository: localhost:5001/rekrutacja_elympics-aspnet_for_elympics:latest
    ports:
      containerPort: 8080
  service:
    type: LoadBalancer
    protocol: TCP
    port: 8888
  env:
    ApplicationSettings:
      NumbersLimit: 10
      RandomNumberRequestUri: "http://golang-for-elympics-service:8081/api/randomNumber"
    ConnectionStrings:
      AppConnectionString: "Host=aspnet-database;Port=5432;Database=NumbersDatabase;Username=myUser;Password=mysecretpassword;"
    ASPNETCORE_ENVIRONMENT: "Development"

postgres:
  name: aspnet-database
  image:
    repository: postgres:16.1
    ports:
      containerPort: 5432
  service:
    type: ClusterIP
    port: 5432
  env:
    POSTGRES_PASSWORD: mysecretpassword
    POSTGRES_USER: myUser
    POSTGRES_DB: NumbersDatabase
  persistence:
    name: numbers-db-volume
    claimName: numbers-db-pvc
    mountPath: /var/lib/postgresql/data
    size: 1Gi

replicaCount: 1