apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.aspnetApp.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.aspnetApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.aspnetApp.name }}
    spec:
      containers:
      - name: {{ .Values.aspnetApp.name }}
        image: {{ .Values.aspnetApp.image.repository }}
        ports:
        - containerPort: {{ .Values.aspnetApp.image.ports.containerPort }}
        env:
          - name: ApplicationSettings__NumbersLimit
            value: {{ .Values.aspnetApp.env.ApplicationSettings.NumbersLimit | quote }}
          - name: ApplicationSettings__RandomNumberRequestUri
            value: {{ .Values.aspnetApp.env.ApplicationSettings.RandomNumberRequestUri }}
          - name: ConnectionStrings__AppConnectionString
            value: {{ .Values.aspnetApp.env.ConnectionStrings.AppConnectionString }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.aspnetApp.env.ASPNETCORE_ENVIRONMENT }}
