apiVersion: v1
kind: Service
metadata:
  name: golang-for-elympics-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app: golang-for-elympics