apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.golangApp.name }}-service
spec:
  type: {{ .Values.golangApp.service.type }}
  ports:
    - protocol: {{ .Values.golangApp.service.protocol }}
      port: {{ .Values.golangApp.service.port }}
      targetPort: {{ .Values.golangApp.image.ports.containerPort }}
  selector:
    app: {{ .Values.golangApp.name }}