apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.golangApp.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.golangApp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.golangApp.name }}
    spec:
      containers:
      - name: {{ .Values.golangApp.name }}
        image: {{ .Values.golangApp.image.repository }}
        ports:
        - containerPort: {{ .Values.golangApp.image.ports.containerPort }}