apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aspnetApp.name }}-lb-service
  labels:
    app: {{ .Values.aspnetApp.name }}-lb-service
spec:
  type: {{ .Values.aspnetApp.service.type }}
  ports:
    - port: {{ .Values.aspnetApp.service.port }}
      targetPort: {{ .Values.aspnetApp.image.ports.containerPort }}
      protocol: {{ .Values.aspnetApp.service.protocol }}
  selector:
    app: {{ .Values.aspnetApp.name }}